/**
 * LQR Gain Scheduler for Hardware
 * 
 * Loads gain schedule from CSV (generated by MATLAB solveLQR.m), performs
 * bilinear interpolation for K(velocity, height), and computes u = -K * x.
 *
 * State:   x = [R, P, Y, Rdot, Pdot, Ydot]'  (roll, pitch, yaw, rates) [rad, rad/s]
 * Control: u = [delta1, delta2, delta3, delta4]'  (canard deflections) [rad]
 * 
 * CSV format: velocity,height,K11,K12,...,K46 (K is 4x6, row-major, 1-indexed)
 */

#ifndef GAIN_SCHEDULER_H
#define GAIN_SCHEDULER_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// LQR dimensions
#define LQR_NUM_STATES  6   // [R, P, Y, Rdot, Pdot, Ydot]
#define LQR_NUM_INPUTS  4   // [delta1, delta2, delta3, delta4]
#define LQR_K_ROWS      LQR_NUM_INPUTS
#define LQR_K_COLS      LQR_NUM_STATES
#define LQR_K_SIZE      (LQR_K_ROWS * LQR_K_COLS)  // 24

/**
 * Gain matrix K (4x6): u = -K * x
 * Access: K[row][col] where row = input index, col = state index
 */
typedef struct {
    float K[LQR_K_ROWS][LQR_K_COLS];
} LQRGains_t;

/**
 * Gain scheduler configuration
 */
typedef struct {
    float vel_min;      // Minimum velocity in table [m/s]
    float vel_max;      // Maximum velocity in table [m/s]
    float vel_step;     // Velocity step size [m/s]
    float h_min;        // Minimum height in table [m]
    float h_max;        // Maximum height in table [m]
    float h_step;       // Height step size [m]
    int num_vel;        // Number of velocity breakpoints
    int num_h;          // Number of height breakpoints
} GainSchedulerConfig_t;

/** Opaque handle to gain scheduler */
typedef struct GainScheduler* GainSchedulerHandle_t;

/**
 * Create and load gain scheduler from CSV file.
 * 
 * @param csvPath Path to lqr_gains.csv
 * @return Handle to scheduler, or NULL on failure
 */
GainSchedulerHandle_t GainScheduler_Create(const char* csvPath);

/**
 * Destroy gain scheduler and free memory.
 * 
 * @param handle Pointer to handle (set to NULL after destroy)
 */
void GainScheduler_Destroy(GainSchedulerHandle_t* handle);

/**
 * Get configuration/info about the loaded gain schedule.
 * 
 * @param handle Scheduler handle
 * @param config Output configuration struct
 * @return true on success
 */
bool GainScheduler_GetConfig(GainSchedulerHandle_t handle, GainSchedulerConfig_t* config);

/**
 * Get interpolated LQR gains for given velocity and height.
 * Uses bilinear interpolation; clamps to table bounds.
 * 
 * @param handle Scheduler handle
 * @param velocity Velocity [m/s]
 * @param height Height/altitude [m]
 * @param gains Output gain matrix (4x6)
 * @return true on success
 */
bool GainScheduler_GetGains(GainSchedulerHandle_t handle, float velocity, float height, LQRGains_t* gains);

/**
 * Compute control output u = -K(vel, h) * x
 * 
 * @param handle Scheduler handle
 * @param velocity Current velocity [m/s]
 * @param height Current height [m]
 * @param x State vector [R, P, Y, Rdot, Pdot, Ydot] (6 elements) [rad, rad/s]
 * @param u Output control vector [delta1..delta4] (4 elements) [rad]
 * @return true on success
 */
bool GainScheduler_ComputeControl(GainSchedulerHandle_t handle, 
                                   float velocity, float height,
                                   const float x[LQR_NUM_STATES], 
                                   float u[LQR_NUM_INPUTS]);

/**
 * Get raw gain at specific grid indices (no interpolation).
 * Useful for debugging/validation.
 * 
 * @param handle Scheduler handle
 * @param vel_idx Velocity index (0-based)
 * @param h_idx Height index (0-based)
 * @param gains Output gain matrix
 * @return true on success
 */
bool GainScheduler_GetGainsAtIndex(GainSchedulerHandle_t handle, 
                                    int vel_idx, int h_idx, 
                                    LQRGains_t* gains);

#ifdef __cplusplus
}
#endif

#endif /* GAIN_SCHEDULER_H */
